version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - .*
      exclude:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: 21
        mavenVersion: 3.9.12
        commands:
          - ./build.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - build
        settings: []
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: search
        strategy: {}
        dependsOn: build_maven
  - name: build-docker
    displayName: 构建镜像
    dependsOn: compile  # 必须等编译完成
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - checkout:
      # 下载上一步编译好的 jar 包
      - step: download@general_artifacts
        name: download_artifact
        displayName: 下载构建产物
        dependArtifact: search
      - step: build@docker
        name: build_search_docker
        displayName: 镜像构建-search
        type: cert
        certificate: '100309595'
        tag: ${GITEE_BRANCH}-1.0-M1-${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./build/tangduosearch/Dockerfile
        context: ./build/tangduosearch
        artifacts: []
        isCache: false
        processorType:
          - amd64
        parameter: {}
        notify: []
        strategy:
          retry: '0'
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: search
        version: 1.0.0.0
        autoIncrement: true
        strategy: {}
